### ISSUE TITLE
maven issue: Invalid parameter user_system

### ISSUE THREAD

**Issue by Boran** [maestrodev/puppet-sonar#7]
This module depends on your maven module, which does not have an issue queue.

 Error 400 on SERVER: Invalid parameter user_system at /etc/puppet/environments/production/manifests/myhost.pp:125 on node jenkins

It doesn't like the User_system is the maven setup (suign the example:
`class { "maven::maven":
    repo => {
      url => "http://repo.maven.apache.org/maven2",
      username => "",
      password => "",
    },
    user                 => "maven",  # if you want to run it as a different user (defaults to root), will create it if not defined
    user_system          => true,    # make the user a system user
    maven_opts           => "",      # anything to add to MAVEN_OPTS in ~/.mavenrc
    maven_path_additions => "",      # anything to add to the PATH in ~/.mavenrc
  } ->`

**Comment by carlossg** [comment]
thanks, updated the README there. There's a list of issues at https://github.com/maestrodev/puppet-maven/issues
