### ISSUE TITLE
Support for version >3

### ISSUE THREAD

**Issue by judoole** [maestrodev/puppet-sonar#8]
Would be nice if support for newest versions could work. 3.6.2 being latest at time of writing, but script only works for 2.14 and lower.

Or are there licensing issues?

**Comment by carlossg** [comment]
pull requests accepted! :)

**Comment by judoole** [comment]
#win for reply :)
@carlossg guess you don't know why it does not work out of the box? So I know where to start digging.

**Comment by brettporter** [comment]
I believe it worked up until 3.5.1, but they renamed in 3.6 and that might be impacting it. Can you elaborate on the error?

**Comment by judoole** [comment]
Hmmm... Could be I was hastily jumping to conclusions here. Using 3.5.1, the sonar.log shows 

> Unable to start JVM: No such file or directory (2)

So I'll start fixing that problem first and report what that will do. Thanks @brettporter.

**Comment by judoole** [comment]
Couldn't get it to work with 3.\* out-of-the-box
Following works brilliantly:

```
class { 'java':
    distribution => 'jdk',
    version      => 'latest',
} ->
class { 'maven::maven' : } ->
class { 'sonar' :
     version      => '2.13',
}
```

Changing version to **3.5.1** creates in an Exception of database dialect. From sonar.log

> org.sonar.api.utils.SonarException: Unable to determine database dialect to use within sonar with dialect null jdbc url jdbc:derby://localhost:1527/sonar;create=true

Seems like Derby has been removed from 3.something. So the fix was to specify a jdbc-connection Sonar had a liking to. Like the default H2. This worked:

```
$jdbc = {
  url               => 'jdbc:h2:tcp://localhost:9092/sonar',
  driver_class_name => 'org.h2.Driver',
  validation_query  => 'select 1',
  username          => 'sonar',
  password          => 'sonar',
}
class { 'java':
        distribution => 'jdk',
        version      => 'latest',
} ->
class { 'maven::maven' : } ->
class { 'sonar' :
  version      => '3.6.2',
  jdbc         => $jdbc,
}
```
